version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/GroShop/app/
  - source: /scripts/
    destination: /home/ec2-user/GroShop/scripts/
  - source: /appspec.yml
    destination: /home/ec2-user/GroShop/
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 180
      runas: ec2-user
  ValidateService:
    - location: scripts/test.sh
      timeout: 180
      runas: ec2-user